import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X, Mail, MessageSquare, HelpCircle, LifeBuoy, Send, Check, ChevronDown,
  Headphones, BookOpen, Clock, AlertCircle, Sparkles
} from 'lucide-react';
import { submitSupportTicket } from '../services/api';

const SUPPORT_EMAIL = 'support@wellnessplatform.com';

const FAQS = [
  {
    q: 'How do I update my health profile?',
    a: 'Click on your profile picture in the top-right corner and select "Edit Profile". You can update your personal details and upload a new avatar there.',
  },
  {
    q: 'How do I schedule a health checkup?',
    a: 'Navigate to the "Checkups & SOS" module from the sidebar, pick an available date and time, and confirm your appointment. You will receive a confirmation notification.',
  },
  {
    q: 'How do I file an insurance claim?',
    a: 'Go to the "My Insurance" module, review your policy details, and click "File Claim". Fill in the claim description and amount — an admin will review and approve or reject it.',
  },
  {
    q: 'How can I contact the HR/Wellness team?',
    a: `You can reach the wellness support team at ${SUPPORT_EMAIL}, or use the live chat in this window for immediate AI-assisted guidance.`,
  },
  {
    q: 'How do I trigger an emergency SOS?',
    a: 'The SOS button is in the main header. Pressing it immediately alerts the admin/HR team with your emergency contact and known health info.',
  },
  {
    q: 'How are my wellness recommendations generated?',
    a: 'Recommendations are generated by an ML model that analyzes your health records — including BMI, sleep, stress, and exercise — to surface personalized, evidence-based wellness plans.',
  },
];

export default function CustomerSupportModal({ user, onClose }) {
  const [activeTab, setActiveTab] = useState('contact'); // contact | faq | chat
  const [form, setForm] = useState({ subject: '', message: '' });
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState('');
  const [openFaq, setOpenFaq] = useState(0);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    if (!form.subject.trim() || !form.message.trim()) {
      setError('Please provide both a subject and a message.');
      return;
    }
    setSubmitting(true);
    try {
      await submitSupportTicket({
        employeeId: user?.employeeId || 'guest',
        employeeName: user?.name || 'Guest',
        subject: form.subject,
        message: form.message,
      });
      setSubmitted(true);
    } catch (err) {
      setError(err.message || 'Failed to submit ticket. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const tabButtonClass = (tab) =>
    `px-4 py-2 rounded-lg text-xs font-semibold transition-all cursor-pointer flex items-center gap-1.5 border ${
      activeTab === tab
        ? 'bg-blue-600 text-white border-blue-600 shadow-sm'
        : 'bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 border-transparent hover:bg-slate-200 dark:hover:bg-slate-700'
    }`;

  const quickActions = [
    {
      icon: MessageSquare,
      title: 'Live Chat',
      desc: 'Chat instantly with our AI wellness assistant.',
      onClick: () => setActiveTab('chat'),
    },
    {
      icon: Mail,
      title: 'Email Support',
      desc: `Write to ${SUPPORT_EMAIL}`,
      onClick: () => (window.location.href = `mailto:${SUPPORT_EMAIL}`),
    },
    {
      icon: BookOpen,
      title: 'Browse FAQ',
      desc: 'Find answers to common questions.',
      onClick: () => setActiveTab('faq'),
    },
  ];

  return (
    <div className="fixed inset-0 z-[200] bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 animate-fadeIn">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        transition={{ type: 'spring', damping: 26, stiffness: 300 }}
        className="bg-white dark:bg-slate-800 rounded-2xl w-full max-w-2xl shadow-2xl border border-slate-200 dark:border-slate-700 max-h-[90vh] flex flex-col overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-100 dark:bg-blue-950/50 rounded-full flex items-center justify-center text-blue-600 dark:text-blue-400">
              <LifeBuoy className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-display font-semibold text-lg leading-tight text-slate-900 dark:text-slate-100">Customer Support</h3>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 font-mono mt-0.5">How can we help you today?</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-full text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
            title="Close Support"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tabs */}
        <div className="px-6 pt-4 flex items-center gap-2 shrink-0">
          <button onClick={() => setActiveTab('contact')} className={tabButtonClass('contact')} >
            <Headphones className="w-3.5 h-3.5" /> Contact
          </button>
          <button onClick={() => setActiveTab('faq')} className={tabButtonClass('faq')} >
            <HelpCircle className="w-3.5 h-3.5" /> FAQ
          </button>
          <button onClick={() => setActiveTab('chat')} className={tabButtonClass('chat')} >
            <MessageSquare className="w-3.5 h-3.5" /> Live Chat
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6">
          {activeTab === 'chat' ? (
            <div className="flex flex-col items-center justify-center py-8 text-center space-y-4">
              <Sparkles className="w-10 h-10 text-blue-500" />
              <div>
                <h4 className="font-semibold text-slate-800 dark:text-slate-100">Launch AI Chat Assistant</h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-sm mx-auto">
                  Our AI assistant can answer questions about wellness, recommendations, insurance, and more — instantly.
                </p>
              </div>
              <button
                onClick={() => {
                  onClose();
                  // Let parent open the chatbot
                  setTimeout(() => {
                    const event = new CustomEvent('open-ai-chat');
                    window.dispatchEvent(event);
                  }, 100);
                }}
                className="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-xl transition-all cursor-pointer shadow-sm flex items-center gap-2"
              >
                <MessageSquare className="w-4 h-4" /> Open Chat Assistant
              </button>
            </div>
          ) : activeTab === 'faq' ? (
            <div className="space-y-3">
              {FAQS.map((faq, i) => {
                const isOpen = openFaq === i;
                return (
                  <div
                    key={i}
                    className="border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden bg-slate-50/50 dark:bg-slate-900/40"
                  >
                    <button
                      onClick={() => setOpenFaq(isOpen ? -1 : i)}
                      className="w-full flex items-center justify-between gap-3 px-4 py-3.5 text-left cursor-pointer"
                    >
                      <span className="text-xs font-semibold text-slate-800 dark:text-slate-100">{faq.q}</span>
                      <ChevronDown
                        className={`w-4 h-4 text-slate-400 shrink-0 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
                      />
                    </button>
                    <AnimatePresence initial={false}>
                      {isOpen && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          transition={{ duration: 0.2 }}
                        >
                          <p className="px-4 pb-4 text-xs text-slate-500 dark:text-slate-400 leading-relaxed font-light">
                            {faq.a}
                          </p>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                );
              })}
            </div>
          ) : (
            /* Contact tab */
            <div className="space-y-6">
              {/* Quick actions */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {quickActions.map((action, i) => {
                  const Icon = action.icon;
                  return (
                    <button
                      key={i}
                      onClick={action.onClick}
                      className="group p-4 bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-700 rounded-xl text-left hover:border-blue-400 dark:hover:border-blue-700 hover:shadow-md transition-all cursor-pointer"
                    >
                      <div className="p-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-blue-600 dark:text-blue-400 w-fit group-hover:bg-blue-50 dark:group-hover:bg-blue-950/40 transition-colors">
                        <Icon className="w-4 h-4" />
                      </div>
                      <div className="mt-3 text-sm font-semibold text-slate-800 dark:text-slate-100">{action.title}</div>
                      <div className="text-xs text-slate-500 dark:text-slate-400 mt-1 leading-relaxed font-light">{action.desc}</div>
                    </button>
                  );
                })}
              </div>

              {/* Submit ticket form */}
              <div className="border border-slate-200 dark:border-slate-700 rounded-xl p-5 space-y-4">
                <div className="flex items-center gap-2">
                  <Clock className="w-4 h-4 text-slate-400" />
                  <h4 className="text-xs font-bold text-slate-700 dark:text-slate-200 uppercase tracking-wider font-mono">
                    Submit a Support Ticket
                  </h4>
                </div>

                {submitted ? (
                  <div className="p-6 text-center space-y-3">
                    <div className="w-12 h-12 mx-auto bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-100 dark:border-emerald-800 rounded-full flex items-center justify-center text-emerald-600 dark:text-emerald-400">
                      <Check className="w-6 h-6" />
                    </div>
                    <h5 className="font-semibold text-base text-slate-800 dark:text-slate-100">Ticket Submitted!</h5>
                    <p className="text-sm text-slate-500 dark:text-slate-400 font-light">
                      Our support team has received your request and will get back to you within 24 hours.
                    </p>
                  </div>
                ) : (
                  <form onSubmit={handleSubmit} className="space-y-5">
                    {error && (
                      <div className="p-3 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 rounded-lg text-xs text-red-700 dark:text-red-300 flex items-start gap-2">
                        <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
                        <span>{error}</span>
                      </div>
                    )}
                    <div>
                      <label className="block text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-1.5 font-mono">
                        Subject
                      </label>
                      <input
                        type="text"
                        value={form.subject}
                        onChange={(e) => setForm({ ...form, subject: e.target.value })}
                        placeholder="e.g. Trouble scheduling a checkup"
                        className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 focus:border-blue-500 focus:bg-white dark:focus:bg-slate-900 rounded-lg text-sm text-slate-800 dark:text-slate-100 placeholder-slate-400 outline-none transition-all"
                      />
                    </div>
                    <div>
                      <label className="block text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-1.5 font-mono">
                        Message
                      </label>
                      <textarea
                        rows="4"
                        value={form.message}
                        onChange={(e) => setForm({ ...form, message: e.target.value })}
                        placeholder="Describe the issue you're facing..."
                        className="w-full px-3.5 py-2.5 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 focus:border-blue-500 focus:bg-white dark:focus:bg-slate-900 rounded-lg text-sm text-slate-800 dark:text-slate-100 placeholder-slate-400 outline-none transition-all resize-none"
                      />
                    </div>
                    <button
                      type="submit"
                      disabled={submitting}
                      className="w-full px-5 py-2.5 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 dark:disabled:bg-slate-700 text-white text-xs font-semibold rounded-xl transition-all cursor-pointer shadow-sm flex items-center justify-center gap-2"
                    >
                      <Send className="w-3.5 h-3.5" />
                      {submitting ? 'Submitting...' : 'Submit Ticket'}
                    </button>
                  </form>
                )}
              </div>

              <div className="p-4 bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-700 rounded-xl text-center">
                <p className="text-[10px] text-slate-400 dark:text-slate-500 font-mono">
                  Prefer email? Write to <span className="font-bold text-blue-600 dark:text-blue-400">{SUPPORT_EMAIL}</span>
                </p>
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
